language: php
sudo: required
dist: precise
php:
    - hhvm
matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
    - php: 5.x
      dist: precise
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y openssl libcppunit-dev libreadline6 libreadline6-dev valgrind realpath libmodule-install-perl
    - git clone https://github.com/yahoo/mdbm.git src_mdbm
before_script:
    - cd src_mdbm/
    - make -j2 
    - make install
    - cd ..
script:
    - phpize
    - make clean
    - ./configure --with-php-config=php-config --with-mdbm=/tmp/mdbm/
    - make -j2
    - make test
